
# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
executors:
  my-executor:
    docker:
      - image: circleci/python:latest
# Orchestrate or schedule a set of jobs
jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run: sudo apt install build-essential
      - run: echo "something"
      - run: sudo apt-get install ninja-build
      - run: |
          cd lib
          wget --no-check-certificate --content-disposition https://github.com/google/googletest
          curl -LJO https://github.com/google/googletest
      - run: |
          cd build
          cmake -G "Ninja" ..
          cmake --build .
          ctest