# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.0
# Use a package of configuration called an orb.
jobs:
  build:
    docker:
      - image: circleci/python:stretch
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install g++ and gcc compilers
          command: sudo apt install build-essential
      - run:
          name: install cmake
          comamnd: echo "something"
      - run:
          name: install ninja  
          command: sudo apt-get install ninja-build
      - run:
          name: download googletest
          command: |
            cd lib
            wget --no-check-certificate --content-disposition https://github.com/google/googletest
            curl -LJO https://github.com/google/googletest
      - run: 
          name: set-up build system and build tests
          command: |
            cd build
            cmake -G "Ninja" ..
            cmake --build .
            ctest

    

# Orchestrate or schedule a set of jobs