# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  build:
    docker:
      - image: circleci/python:latest

    working_directory: ~/repo

    steps:
      - checkout
    run:
      name: download googletest
      command: |
        wget --no-check-certificate --content-disposition https://github.com/google/googletest
        curl -LJO https://github.com/google/googletest
    
    run:
      name: install conan
      command: pip install conan
# Orchestrate or schedule a set of jobs